[project]
name = "gmonitorbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram==3.20",
    "faststream[cli,kafka]>=0.5.39",
    "pydantic-settings==2.9.1",
]
