name: Deploy

on: [ push ]

jobs:
 deploy:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Deploy
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         port: ${{ secrets.PORT }}
         script: |
           cd /opt/gmonitor-all
           git pull
           git submodule update
           docker compose up --build -d